safe: true
highlighter: pygments
lsi: false
title: huonw@github
markdown: kramdown

kramdown:
   footnote_nr: 0

breadcrumb_list: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15]

defaults:
  -
     scope:
       path: ""
       type: "posts"
     values:
       layout: "default"
       breadcrumb_limit: 2
